trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# 1️⃣ Install dependencies
- script: |
    npm ci
  displayName: "Install Dependencies"

# 2️⃣ Build the Vite app
- script: |
    echo "Building with API Key..."
    npm run build
  displayName: "Build Vite App"
  env:
    VITE_API_KEY: $(VITE_API_KEY)


# 3️⃣ Publish build artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'dist'
    artifact: 'weather-frontend'
  displayName: "Publish Frontend Build Artifact"

# 4️⃣ Deploy to Azure Static Web App
- task: AzureStaticWebApp@0
  inputs:
    app_location: 'dist'
    api_location: ''
    output_location: 'dist'
    azure_static_web_apps_api_token: '$(DEPLOYMENT_TOKEN)'
  displayName: "Deploy to Azure Static Web App"
