trigger:
- main   # Replace with your branch if needed

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Checkout code
- checkout: self
  displayName: 'Checkout source code'

# Step 2: Set up Node.js
- task: UseNode@1
  inputs:
    version: '18.x'
  displayName: 'Set up Node.js'

# Step 3: Install dependencies
- script: |
    npm install
  displayName: 'Install dependencies'

# Step 4: Build React app
- script: |
    npm run build
  displayName: 'Build React app'

# Step 5: Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'weather'         # Your service connection name
    appName: 'web-gaaqhcdjlahsg'         # Your Azure Web App name
    package: '$(System.DefaultWorkingDirectory)/build'
  displayName: 'Deploy React app to Azure Web App'
